# Generated by Django 4.2.16 on 2024-11-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avg_win_point',
            field=models.FloatField(null=True),
        ),
    ]
