# Generated by Django 4.2.16 on 2024-11-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameApp', '0002_alter_gamerecord_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerecord',
            name='emotion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='total_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
