# Generated by Django 4.2.16 on 2024-11-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameApp', '0003_gamerecord_emotion_gamerecord_total_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerecord',
            name='recommend_movie_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='recommend_movie_theme',
            field=models.TextField(blank=True, null=True),
        ),
    ]
